{"name": "test_broken", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'broken.json'", "trace": "self = <test_allure_feature.TestLogin object at 0x0000026E922AD8D0>\n\n    @allure.severity(allure.severity_level.TRIVIAL)\n    @allure.story(\"测试broken用例\")\n    @allure.issue(\"https://www.cnblogs.com/linuxchao/\", \"错误链接\")\n    def test_broken(self):\n        \"\"\"broken\"\"\"\n>       with open(\"broken.json\", \"r\", encoding='utf8') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'broken.json'\n\ntest_allure_feature.py:164: FileNotFoundError"}, "description": "broken", "start": 1582701229551, "stop": 1582701229551, "uuid": "d98a23bf-ef70-4d48-af6b-8d3ef58678ad", "historyId": "820cfc31a96c11119c79600043e38f41", "testCaseId": "4075673186e1f75e7dc322bf557695b4", "fullName": "test_allure_feature.TestLogin#test_broken", "labels": [{"name": "severity", "value": "trivial"}, {"name": "story", "value": "测试broken用例"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_allure_feature"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-1TP29R9"}, {"name": "thread", "value": "14420-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_feature"}], "links": [{"type": "issue", "url": "https://www.cnblogs.com/linuxchao/", "name": "错误链接"}]}